services:
  postgresql:
    image: bitnami/postgresql:14
    labels:
      org.springframework.boot.service-connection: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: survey
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: survey
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
    - 9411:9411